export enum AppRoute {
  Base = '',
  Home = 'home',
  Vacancies = 'vacancies',
  Applicants = 'applicants',
  Projects = 'projects',
  Interviews = 'interviews',
  Analytics = 'analytics',
  TaskManagement = 'taskManagement',
  UserManagement = 'user-management',
  Templates = 'templates',
  Pools = 'pools',
  Login = 'login',
  Registration = 'registration',
  ConfirmEmail = 'confirm-email',
  SuccessfulRegistration = 'successful-registration',
  ResetPassword = 'reset-password',
  ResendEmail = 'resend-email',
}
