export enum AppRoute {
  Base = '',
  Home = 'home',
  Vacancies = 'vacancies',
  Applicants = 'applicants',
  Interviews = 'interviews',
  Analytics = 'analytics',
  TaskManagement = 'taskManagement',
  Templates = 'templates',
  Login = 'login',
  Registration = 'registration',
  ConfirmEmail = 'confirm-email',
  SuccessfulRegistration = 'successful-registration',
  ResetPassword = 'reset-password',
}
