version: "3.8"
services:
  ats_api:
    container_name: 'ats_api'
    image: docker.pkg.github.com/binarystudioacademy/bsa-2021-ats/ats-api:latest
    restart: on-failure
    ports:
      - "5050:80"
    networks:
      - backend
    env_file:
      - ../.env/ats_api.env
  ats_elastic_server:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.13.4"
    restart: on-failure
    container_name: 'ats_elastic_server'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment: 
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - backend
  ats_database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: "ats_database"
    ports:
      - 1433:1433
    networks:
      - backend
    env_file:
      - ../.env/ats_database.env
    volumes:
      - ats_database-data:/var/opt/mssql

  ats_mongodb:
    image: mongo
    container_name: ats_mongodb
    env_file:
      - ../.env/ats_mongodb.env
    ports:
      - 27017:27017
    volumes:
      - ats_mongodb-data:/data/db

  ats_frontend:
    container_name: 'ats_frontend'
    image: docker.pkg.github.com/binarystudioacademy/bsa-2021-ats/ats-frontend:latest
    restart: on-failure
    ports:
      - 80:80
    networks:
      - backend
      - frontend

volumes:
  ats_database-data: {}
  ats_mongodb-data: {}

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
