version: '3.8'
services:
  ats_api:
    build:
      context: ../backend/src/
      dockerfile: Dockerfile
    container_name: 'ats_api'
    restart: on-failure
    ports:
      - "5050:80"
    networks:
      - backend
    env_file:
      - ../.env/ats_api.env

  ats_database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: 'ats_database'
    ports:
        - 1433:1433
    networks:
        - backend
    env_file:
      - ../.env/ats_database.env
    volumes: 
      - ats_database-data:/var/opt/mssql

  ats_frontend:
    build: ../frontend/ATS
    container_name: 'ats_frontend'
    restart: on-failure
    ports:
        - 4200:80
    networks:
        - backend
        - frontend

volumes:
  ats_database-data:

networks:
  backend:
      driver: bridge
  frontend:
      driver: bridge