version: "3.8"
services:
  ats_database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: ats_database
    ports:
      - 1433:1433
    networks:
      - backend
    env_file:
      - ../.env/ats_database.env
    volumes:
      - ats_database-data:/var/opt/mssql
  ats_elastic_server:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.13.4"
    restart: on-failure
    container_name: 'ats_elastic_server'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment: 
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - backend
  ats_mongodb:
    image: mongo
    container_name: ats_mongodb
    env_file:
      - ../.env/ats_mongodb.env
    ports:
      - 27017:27017
    volumes:
      - ats_mongodb-data:/data/db
volumes:
  ats_database-data: {}
  ats_mongodb-data: {}

networks:
  backend:
    driver: bridge
