version: "3.8"
services:
  ats_elastic_server:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.13.4"
    restart: on-failure
    container_name: 'ats_elastic_server'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - esdata1:/usr/share/elasticsearch/data:rw
    environment: 
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - backend

volumes:
  esdata1:
    driver: local

networks:
  backend:
    driver: bridge
