name: lint

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - feature-ci-cd

jobs:
  setup-node-modules:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/ATS
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      id: node-modules-cache
      with:
        path: 'node_modules'
        key: node_modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: npm run install

  lint:
    needs: setup-node-modules
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/ATS
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Load dependencies
      uses: actions/cache@v2
      with:
        path: 'node_modules'
        key: node_modules-${{ hashFiles('package-lock.json') }}

    - name: Lint
      run: npm run lint