name: lint

on:
  pull_request:
    branches:
      - develop

jobs:
  setup-node-modules:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/ATS
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      id: node-modules-cache
      with:
        path: 'node_modules'
        key: node_modules-${{ hashFiles('package-lock.json') }}

    - name: install dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: npm run install

  lint:
    needs: setup-node-modules
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/ATS
    steps:
    - uses: actions/checkout@v2

    - name: load node_modules
      uses: actions/cache@v2
      with:
        path: 'node_modules'
        key: node_modules-${{ hashFiles('package-lock.json') }}

    - name: lint
      run: npm run lint